
function Td1() {
    return (
        <td width="470" style={{borderStyle: "none", borderWidth: "medium"}}>
          <p style={{lineHeight: "200%"}}>
            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>
              Accounting
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>
            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>
              Advertising Management
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>
              Business &amp; Economics
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>
              Business Ethics
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>
              Business Intelligence
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>
              Business Information Systems
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>
              Business Law
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>
              Business Performance Management
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>
              Business Statistics
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>
              Change Management
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>
              Communications Management
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>
              Comparative Economic Systems
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>
              Consumer Behavior
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>
              Corporate Finance and Governance
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>
              Corporate Governance
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>
              Cost Management
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>
              Decision Sciences
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>
              Development Planning and Policy
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>
              Economic Development
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>
              Economic Methodology
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>
              Economic Policy
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>
              Economic Systems
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>
              Entrepreneurship
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>
              Finance &amp; Investment
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>
              Financial Economics
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>
              Global Business
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>
              Growth; Aggregate Productivity
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>
              Household Behavior and Family Economics
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>
              Human Resource
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>
              Industrial and Manufacturing Engineering
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>
              Information Systems
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>
              Information Technology Management
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>
              International Business
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>
              International Economics
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>
              International Finance
            </span>
          </p>
        </td>
    );
  }

  export default Td1;
