

function Td2() {
    return (
        <td style={{borderStyle: "none", borderWidth: "medium"}}>
          <p style={{lineHeight: "200%"}}>
          <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>
              Labor Economics<span className="Apple-converted-space">&nbsp;</span>
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>
            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>              Labor Relations &amp; Human Resource Management
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>
            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>              Law and Economics
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>
            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>              Management Information Systems
              <span className="Apple-converted-space">&nbsp;</span>
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>
            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>              Management Science
              <span className="Apple-converted-space">&nbsp;</span>
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>
            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>              Market Structure and Pricing
              <span className="Apple-converted-space">&nbsp;</span>
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>
            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>              Marketing Research and Strategy
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>
            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>              Marketing Theory and Applications
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>
            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>          Operations Research
              <span className="Apple-converted-space">&nbsp;</span>
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>
            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>   Organizational Behavior &amp; Theory
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>
            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>  Organizational Communication
              <span className="Apple-converted-space">&nbsp;</span>
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>
            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>  Prices, Business Fluctuations, and Cycles
              <span className="Apple-converted-space">&nbsp;</span>
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>
            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>  Product Management
              <span className="Apple-converted-space">&nbsp;</span>
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>
            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>  Production and Organizations
              <span className="Apple-converted-space">&nbsp;</span>
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>
            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>  Production/Operations Management
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>
            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>  Public Administration and Small Business Entrepreneurship
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>
            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>   Public Choice<span className="Apple-converted-space">&nbsp;</span>
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>
            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>   Public Economics and Finance
              <span className="Apple-converted-space">&nbsp;</span>
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>
            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>   Public Relations<span className="Apple-converted-space">&nbsp;</span>
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>
            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>  Public Responsibility and Ethics
              <span className="Apple-converted-space">&nbsp;</span>
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>
            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>  Regulatory Economics
              <span className="Apple-converted-space">&nbsp;</span>
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>
            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>   Resource Management
              <span className="Apple-converted-space">&nbsp;</span>
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>
            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>  Strategic Management
              <span className="Apple-converted-space">&nbsp;</span>
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>
            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}> Strategic Management Policy
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>
            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>   Stress Management<span className="Apple-converted-space">&nbsp;</span>
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>
            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>  Supply Chain Management
              <span className="Apple-converted-space">&nbsp;</span>
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>
            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>   Systems Management
              <span className="Apple-converted-space">&nbsp;</span>
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>
            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>   Systems Thinking<span className="Apple-converted-space">&nbsp;</span>
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>
            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>  Taxes (related areas of taxes)
              <span className="Apple-converted-space">&nbsp;</span>
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>
            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>    Technological Change; Research and Development
              <span className="Apple-converted-space">&nbsp;</span>
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>
            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>   Technology &amp; Innovation
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>
            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}> Time Management<span className="Apple-converted-space">&nbsp;</span>
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>
            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>  Total Quality Management
              <span className="Apple-converted-space">&nbsp;</span>
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>
            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>Travel/Transportation/Tourism
              <span className="Apple-converted-space">&nbsp;</span>
            </span>
            <br style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)"}}/>
            <span style={{color: "rgb(51, 51, 51)", fontFamily: "Arial, Helvetica, sans-serif", fontSize: "14px", fontStyle: "normal", fontVariantLigatures: "normal", fontVariantCaps: "normal", fontWeight: "normal", letterSpacing: "normal", orphans: "2", textAlign: "start", textIndent: "0px", textTransform: "none", whiteSpace: "normal", widows: "2", wordSpacing: "0px", webkitTextStrokeWidth: "0px", backgroundColor: "rgb(255, 255, 255)", display: "inline !important", float: "none"}}>  Welfare Economics
            </span>
          </p>
        </td>
    );
  }

  export default Td2;
  